//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by IPMsg.rc
//
#define APPLY_BUTTON                    3
#define IDS_BROADCAST                   100
#define IDS_MULTICAST                   101
#define IDS_UNICAST                     102
#define IDS_UNIABSENCE                  111
#define IDS_KEYOPEN                     112
#define IDS_FILEATTBTN                  113
#define IDS_INTERCEPT                   114
#define IDS_FONTSET                     115
#define IDS_SIZESET                     116
#define IDS_SAVEPOS                     117
#define IDS_SAVEFILE                    118
#define IDS_TRANSSTOP                   119
#define IDS_PREPARETRANS                120
#define IDS_CREATEFAIL                  121
#define IDS_WRITEFAIL                   122
#define IDS_DECRYPTERR                  123
#define IDS_PATHTOOLONG                 124
#define IDS_NOTSAFEPATH                 125
#define IDS_CANTEXEC                    126
#define IDS_EXECPROGRAM                 127
#define IDS_OPENFILEPRGFLTR             128
#define IDS_CANTAUTH                    129
#define IDS_NOTSAMEPASS                 130
#define IDS_IPMSGURL                    131
#define IDS_LOGALERT                    135
#define IDS_FIRE                        136
#define IDS_ABSENCEQUERY                137
#define IDS_USERNUM                     138
#define IDS_BROADCASTHEAD               139
#define IDS_RETRYSEND                   140
#define IDS_BROADCASTSEND               141
#define IDS_GROUPSELECT                 142
#define IDS_DEFAULTSET                  143
#define IDS_BROADCASTMSG                144
#define IDS_BUSYMSG                     145
#define IDS_MOVETO                      146
#define IDS_SELECT                      147
#define IDS_DEFAULTDISP                 148
#define IDS_USER                        149
#define IDS_DISPPRIORITY                150
#define IDS_NODISP                      151
#define IDS_MEMBERCOUNT                 152
#define IDS_MEMBERCOUNTDEF              153
#define IDS_TMPNODISPDISP               154
#define IDS_RESETPRIORITY               155
#define IDS_SORTFILTER                  156
#define IDS_FINDDLG                     157
#define IDS_FILEATTACHMENU              158
#define IDS_FOLDERATTACHMENU            159
#define IDS_SAVECOLUMN                  160
#define IDS_COMCTL                      161
#define IDS_CANTGETORDER                162
#define IDS_MEMBERDISP                  163
#define IDS_PRIORITY                    164
#define IDS_ABSENCE                     165
#define IDS_GROUP                       166
#define IDS_HOST                        167
#define IDS_LOGON                       168
#define IDS_IPADDR                      169
#define IDS_ADDFILE                     170
#define IDS_OPENFILEALLFLTR             171
#define IDS_FOLDERATTACH                172
#define IDS_PROPORTIONALFONT            173
#define IDS_BROADCASTLOG                174
#define IDS_AUTORETLOG                  175
#define IDS_MULTICASTLOG                176
#define IDS_PASSWDLOG                   177
#define IDS_SECRETLOG                   178
#define IDS_FILEATTACH                  179
#define IDS_USEWIN32                    182
#define IDS_IPMSG                       183
#define IDS_PASSWDNOTSET                184
#define IDS_WINEDITION                  185
#define IDS_WIN16EDITION                186
#define IDS_NOTABSENCE                  188
#define IDS_FILEEXTERR                  189
#define IDS_CANTOPENLOG                 190
#define IDS_ABSENCEMENU                 191
#define IDS_ABSENCELIFT                 192
#define IDS_ABSENCESET                  193
#define IDS_DOWNLOAD                    194
#define IDS_SETENVHOST                  195
#define IDS_HOSTUNREACH                 196
#define IDS_DEFABSENCE1                 197
#define IDS_DEFABSENCE2                 198
#define IDS_DEFABSENCE3                 199
#define IDS_DEFABSENCE4                 200
#define IDS_DEFABSENCE5                 201
#define IDS_DEFABSENCE6                 202
#define IDS_DEFABSENCE7                 203
#define IDS_DEFABSENCE8                 204
#define IDS_DEFABSENCEHEAD1             205
#define IDS_DEFABSENCEHEAD2             206
#define IDS_DEFABSENCEHEAD3             207
#define IDS_DEFABSENCEHEAD4             208
#define IDS_DEFABSENCEHEAD5             209
#define IDS_DEFABSENCEHEAD6             210
#define IDS_DEFABSENCEHEAD7             211
#define IDS_DEFABSENCEHEAD8             212
#define IDS_CANTRESOLVE                 213
#define IDS_FILENAME                    214
#define IDS_SIZE                        215
#define IDS_LOCATION                    216
#define IDS_LUMPBUTTON                  217
#define IDS_FILEINFO                    218
#define IDS_PREVBUTTON                  219
#define IDS_NEXTBUTTON                  220
#define IDS_OVERWRITE                   221
#define IDS_ATTENTION                   222
#define IDS_DIRSAVE                     223
#define IDS_OPENFILESND                 224
#define IDS_OPENFILESNDFLTR             225
#define IDS_OPENFILEICON                226
#define IDS_OPENFILEICONFLTR            227
#define IDS_OPENFILELOG                 228
#define IDS_OPENFILELOGFLTR             229
#define IDS_EXCEPTIONLOG                230
#define IDS_UNDO                        232
#define IDS_CUT                         233
#define IDS_COPY                        234
#define IDS_PASTE                       235
#define IDS_PASTE_TEXT                  236
#define IDS_PASTE_BMP                   237
#define IDS_DELETE                      238
#define IDS_SELECTALL                   239
#define IDS_IPMSGHELP                   240
#define IDS_OPENFIN                     241
#define IDS_DELAYOPEN                   242
#define IDS_RECVMSG                     243
#define IDS_LRUUSER                     244
#define IDS_ENCRYPT                     250
#define IDS_ENCRYPT2                    251
#define IDS_ENCRYPT2_SIGNED             252
#define IDS_ENCRYPT2_ERROR              253
#define IDS_UNAUTHORIZED                254
#define IDS_UNAUTHORIZED_TITLE          255
#define IDS_SIGN_ERROR_TITLE            256
#define IDS_TOOMANY_CLIP                257
#define IDS_CLIPDESTROY                 258
#define IDS_WITHCLIP                    259
#define IDS_OPENCHECK_NONE              260
#define IDS_OPENCHECK_BALLOON           261
#define IDS_OPENCHECK_ICON              262
#define IDS_OPENCHECK_DLG               263
#define IDS_HISTUSER                    264
#define IDS_HISTODATE                   265
#define IDS_HISTID                      266
#define IDS_HISTSDATE                   267
#define IDS_LIMITED                     270
#define IDS_DIRECTED                    271
#define IDS_BOTH                        272
#define IDS_IMAGEPASTEMENU              273
#define IDS_FILEWITHCLIP                274
#define IDS_UNOPENED                    275
#define IDS_UNKNOWN                     276
#define IDS_EMPTYMSG                    277
#define IDS_CAPTION                     278
#define IDS_CAPTIONADD                  279
#define IDS_TOOMANYLRU                  280
#define IDS_OPENINFO                    281
#define IDS_UNOPENINFO                  282
#define IDS_SETUP_SHEET1                301
#define IDS_SETUP_SHEET2                302
#define IDS_SETUP_SHEET3                303
#define IDS_SETUP_SHEET4                304
#define IDS_SETUP_SHEET5                305
#define IDS_SETUP_SHEET6                306
#define SEND_DIALOG                     501
#define SETUP_DIALOG                    503
#define IPMSG_ICON                      505
#define RECEIVE_DIALOG                  506
#define MAIN_MENU                       507
#define RECV_ICON                       508
#define MENU_FILEADD                    509
#define MENU_FOLDERADD                  510
#define MENU_IMAGEPASTE                 511
#define ABOUT_DIALOG                    512
#define LOG_DIALOG                      515
#define PASSWORD_DIALOG                 517
#define PASSWDCHANGE_DIALOG             518
#define MESSAGE_DIALOG                  520
#define SENDFONT_MENU                   521
#define RECVFONT_MENU                   522
#define SIZE_MENU                       523
#define SENDSIZE_MENU                   524
#define IPMSG_ACCEL                     525
#define ABSENCE_DIALOG                  527
#define URL_DIALOG                      528
#define SORT_DIALOG                     544
#define FILTER_DIALOG                   548
#define ABSENCE_ICON                    555
#define IPMSGV1ABS_ICON                 556
#define IPMSGV1_ICON                    557
#define FIND_DIALOG                     558
#define FILE_DIALOG                     559
#define SUSPEND_DIALOG                  560
#define SHARE_DIALOG                    561
#define TRANSEND_DIALOG                 562
#define FILEABS_ICON                    563
#define PLUGIN_DIALOG                   564
#define FILE_ICON                       566
#define SETUP_SHEET1                    571
#define SETUP_SHEET2                    572
#define SETUP_SHEET3                    573
#define SETUP_SHEET4                    574
#define SETUP_SHEET5                    575
#define SETUP_SHEET6                    576
#define DUMMYPIC_BITMAP                 590
#define HISTORY_DIALOG                  591
#define MENU_ICON                       592
#define IPMSGV2_ICON                    593
#define SETUP_MAIN_SEET                 594
#define IPMSGV2ABS_ICON                 595
#define SEND_EDIT                       1001
#define SECRET_CHECK                    1004
#define PASSWORD_CHECK                  1005
#define ABNORMALBTN_CHECK               1006
#define ONECLICK_CHECK                  1007
#define NOBEEP_CHECK                    1015
#define OPEN_CHECK                      1017
#define QUOTE_CHECK                     1018
#define LOGFILE_BUTTON                  1019
#define BROADCAST_LIST                  1020
#define MAINICON_BUTTON                 1021
#define REVICON_BUTTON                  1022
#define ABSENCE_EDIT                    1023
#define DEL_BUTTON                      1024
#define ADD_BUTTON                      1025
#define NOPOPUP_CHECK                   1026
#define PASSWORD_EDIT                   1027
#define RECV_HEAD                       1029
#define RECV_HEAD2                      1030
#define RECV_EDIT                       1031
#define SOUNDFILE_BUTTON                1032
#define BROADCAST_EDIT                  1033
#define NICKNAME_EDIT                   1034
#define NEWPASSWORD_EDIT                1035
#define NEWPASSWORD_EDIT2               1036
#define HOST_LIST                       1045
#define MEMBERCNT_TEXT                  1051
#define OPEN_BUTTON                     1052
#define RECV_TITLE                      1053
#define NOERASE_CHECK                   1054
#define PLUGIN_BUTTON                   1055
#define ABSENCENONPOPUP_CHECK           1056
#define LOG_BUTTON                      1057
#define CONTROLIME_CHECK                1058
#define SHELLEXEC_CHECK                 1059
#define LOG_CHECK                       1060
#define MSGMINIMIZE_CHECK               1061
#define LOG_EDIT                        1062
#define PASSWDLOG_CHECK                 1063
#define REFRESH_BUTTON                  1064
#define LOG_GROUP                       1065
#define MAINICON_EDIT                   1066
#define REVICON_EDIT                    1067
#define PASSWORD_BUTTON                 1068
#define SORT_BUTTON                     1069
#define DIALUP_CHECK                    1070
#define NICKNAME_CHECK                  1071
#define MESSAGE_TEXT                    1073
#define IPADDR_CHECK                    1074
#define SOUND_EDIT                      1075
#define LOGON_CHECK                     1076
#define GROUPDISP_CHECK                 1080
#define GROUP_COMBO                     1081
#define URL_EDIT                        1082
#define QUOTE_EDIT                      1083
#define LOGUTF8_CHECK                   1084
#define OLDPASSWORD_EDIT                1085
#define IMAGESAVE_CHECK                 1086
#define HOST_CHECK                      1087
#define PRIORITY_CHECK                  1088
#define URL_BUTTON                      1090
#define SEPARATE_STATIC                 1091
#define DEFAULTURL_CHECK                1092
#define URL_LIST                        1093
#define GROUP_CHECK                     1108
#define USER_RADIO                      1109
#define IPADDR_RADIO                    1110
#define HOST_RADIO                      1111
#define ICMP_CHECK                      1113
#define KANJI_CHECK                     1114
#define SUBREV_CHECK                    1115
#define NAMEDISPLIMIT_CHECK             1116
#define GROUPREV_CHECK                  1117
#define ABSENCE_LIST                    1118
#define ABSENCEHEAD_EDIT                1122
#define NAMEDISP_EDIT                   1126
#define HOTKEY_CHECK                    1129
#define SET_BUTTON                      1130
#define PRIORITYDISP_CHECK              1131
#define ABSENCEINIT_BUTTON              1132
#define FILTER_BUTTON                   1133
#define FILTER_LIST                     1134
#define CLOSE_BUTTON                    1142
#define GRIDLINE_CHECK                  1145
#define ALLFIND_CHECK                   1153
#define FIND_COMBO                      1155
#define FILE_BUTTON                     1158
#define BMP_BUTTON                      1160
#define FILE_LIST                       1161
#define ADD_EDIT                        1162
#define FOLDER_BUTTON                   1163
#define FILE_STATIC                     1164
#define MODIFY_CHECK                    1165
#define SHARE_LIST                      1166
#define EXEC_BUTTON                     1167
#define IPMSGWEB_BUTTON                 1168
#define ACTIVATE_BUTTON                 1169
#define DEACTIVATE_BUTTON               1170
#define SETTING_BUTTON                  1171
#define PLUGIN_LIST                     1172
#define MENU_BUTTON                     1175
#define BALLOONNOTIFY_CHECK             1177
#define ABOUT_TEXT                      1178
#define LCID_CHECK                      1179
#define IDC_BITMAP                      1180
#define BMPDEL_BUTTON                   1181
#define VSEPARATE_STATIC                1182
#define CLIPMODE_CHECK                  1185
#define CLIPCONFIRM_CHECK               1186
#define IMAGE_BUTTON                    1187
#define OPENCHECK_COMBO                 1189
#define HISTORY_LIST                    1192
#define CLEAR_BUTTON                    1193
#define EXTBROADCAST_COMBO              1195
#define MENU_CHECK                      1197
#define DETAIL_BUTTON                   1199
#define OPENED_CHECK                    1201
#define SETUP_LIST                      1202
#define SOUNDPLAY_BUTTON                1205
#define RECVLOGON_CHECK                 1206
#define RECVLOGON_CHECK2                1207
#define SENDDETAIL_BUTTON               1208
#define LOGONLOG_CHECK                  1209
#define RECVIPADDR_CHECK                1210
#define FINDDLGIME_CHECK                1211
#define OPEN_COMBO                      1212
#define LRUUSER_EDIT                    1215
#define MENU_SETUP                      10001
#define MENU_EXIT                       10003
#define MENU_ABOUT                      10008
#define MENU_LOGIMGOPEN                 10010
#define MENU_ACTIVEWIN                  10011
#define MENU_ABSENCE                    10012
#define MENU_NOPOPUP                    10013
#define MENU_LOGOPEN                    10014
#define MENU_SAVESIZE                   10015
#define MENU_NORMALSIZE                 10016
#define MENU_LISTFONT                   10017
#define MENU_EDITFONT                   10018
#define MENU_DEFAULTFONT                10019
#define SEND_ACCEL                      10020
#define HIDE_ACCEL                      10021
#define MENU_SAVEPOS                    10023
#define MENU_MEMBERDISP                 10024
#define MENU_ABSENCEEX                  10030
#define MENU_SHARE                      10031
#define MENU_HEADFONT                   10032
#define MENU_VERSION                    10033
#define MENU_OPENHISTDLG                10034
#define MISC_ACCEL                      10035
#define MENU_SAVECOLUMN                 10036
#define MENU_FINDDLG                    10037
#define MENU_ABSENCE_START              11000
#define MENU_PRIORITY_RESET             11100
#define MENU_PRIORITY_HIDDEN            11101
#define MENU_PRIORITY_DISP              11103
#define MENU_PRIORITY_START             11110
#define MENU_LRUUSER                    12000
#define MENU_GROUP_START                20000
#define ALLSELECT_ACCEL                 30036
#define MENU_HELP                       30037
#define MENU_HELP_HISTORY               30038

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        596
#define _APS_NEXT_COMMAND_VALUE         30039
#define _APS_NEXT_CONTROL_VALUE         1216
#define _APS_NEXT_SYMED_VALUE           2001
#endif
#endif
